# Generated by Django 5.2 on 2025-04-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('preco', models.FloatField()),
                ('validade', models.CharField(max_length=10)),
                ('quantidade', models.ImageField(upload_to='')),
            ],
        ),
    ]
