# Generated by Django 5.2 on 2025-06-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0002_alter_produto_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(max_length=30),
        ),
    ]
