# Generated by Django 5.2 on 2025-12-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0004_produto_altura_produto_cor_produto_largura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='largura',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='origem',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='profundidade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='validade',
        ),
        migrations.AddField(
            model_name='produto',
            name='estado',
            field=models.CharField(choices=[('boa', 'Boa'), ('excelente', 'Excelente'), ('medio', 'Médio')], default='boa', max_length=10),
        ),
    ]
