# Generated by Django 5.2 on 2025-12-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0005_remove_produto_altura_remove_produto_cor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(choices=[('volkswagen', 'Volkswagen'), ('hyundai', 'Hyundai'), ('nissan', 'Nissan'), ('toyota', 'Toyota'), ('chevrolet', 'Chevrolet'), ('fiat', 'Fiat'), ('byd', 'BYD')], default='volkswagen', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='modelo',
            field=models.CharField(default='Modelo', max_length=50),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('eletrico', 'Elétrico'), ('hibrido', 'Híbrido'), ('combustao', 'Combustão')], default='combustao', max_length=10),
        ),
    ]
