# Generated by Django 5.2 on 2025-12-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0006_remove_produto_nome_remove_produto_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ano_fabricacao',
            field=models.IntegerField(default=2023),
        ),
    ]
