# Generated by Django 5.2 on 2025-12-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0007_produto_ano_fabricacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
