# Generated by Django 5.2 on 2025-12-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0009_produto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cor',
            field=models.CharField(default='Branco', max_length=20),
        ),
    ]
