# Generated by Django 5.2 on 2026-01-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0010_produto_cor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='foto',
        ),
        migrations.AddField(
            model_name='produto',
            name='quilometragem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estado',
            field=models.CharField(choices=[('boa', 'Boa'), ('excelente', 'Excelente')], default='boa', max_length=10),
        ),
    ]
